spring.application.name=TrainSystem
spring.datasource.url=jdbc:h2:mem:traindb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always

# Configurare JavaMailSender pentru Mailtrap
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=88ea3ffeb86838
spring.mail.password=edbf88b1e77972
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Optional: Aceasta linie amana rularea data.sql pana cand tabelele sunt create de Hibernate
spring.jpa.defer-datasource-initialization=true
